root: true
extends: ['@typescord', prettier]
plugins: [prettier]
parserOptions:
  project: tsconfig.json
rules:
  prettier/prettier: error
  unicorn/no-null: off
  unicorn/numeric-separators-style: off
env:
  node: true
  es2020: true
