name: Continuous Integration
on:
  push:
    branches: [main]
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build --noEmit

      - name: Test
        run: yarn test && yarn test-coverage

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v2

      - name: Benchmark
        run: yarn benchmark
